Request body: {"destination":"Ub4a54afea3b4ba8221292907b6fee04a","events":[{"type":"message","message":{"type":"text","id":"521130094056702241","quoteToken":"5mgtlvUv1G2J5abw_TiNEnItdfonMPmA_B8lrN-fEszN-4_SvYqjlUEuH5RJvv-fzT4DXthBQt8q31TEEOLp7MvcAdYDriqZP9-48pVYDOdmKu81WuvAG5anhMiJoDcqt_4mCHJyBBxfk-1ZgkaVKQ","text":"いえい"},"webhookEventId":"01J52S2WN3J6DGHW5FFXR9SYTD","deliveryContext":{"isRedelivery":false},"timestamp":1723449045393,"source":{"type":"user","userId":"U82d6fea100d7148c13eb8ccd074e0433"},"replyToken":"90479bd53234412abbd06e314ffd2168","mode":"active"}]}
Request body: {"destination":"Ub4a54afea3b4ba8221292907b6fee04a","events":[{"type":"message","message":{"type":"text","id":"521130288152838498","quoteToken":"4jTRky07AIaj359L5ePk8G7xGGPbCon5tDJ2OguAcRtoLBqmgUcZw67VRLWHo6a56O6ic-EgaLNP0LZ91xcdwGBsit0AuNbH-Ji2ZCpbFBhfwdIHVneY421n4H-3GwKgUoXRhQO82aWM9AqbGlHkLQ","text":"もしもし"},"webhookEventId":"01J52S6DFPWY3AR071A50KXBFM","deliveryContext":{"isRedelivery":false},"timestamp":1723449161153,"source":{"type":"user","userId":"Uddeb94b203b625ed50f27d83e9656583"},"replyToken":"d57c9e36ddf1411cbd3e81305e5bd4a2","mode":"active"}]}
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 44, in callback
    app.logger.info("Request body: " + body.event[0].source.userId)
                                       ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'event'
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 46, in callback
    app.logger.info("Request body: " + body_json.event[0].source.userId)
                                       ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'event'
Request body: U82d6fea100d7148c13eb8ccd074e0433
Request body: Uddeb94b203b625ed50f27d83e9656583
Request body: U82d6fea100d7148c13eb8ccd074e0433
Request body: U82d6fea100d7148c13eb8ccd074e0433
Request body: U82d6fea100d7148c13eb8ccd074e0433
Request body: U82d6fea100d7148c13eb8ccd074e0433
Request body: U82d6fea100d7148c13eb8ccd074e0433
Request body: {"destination":"Ub4a54afea3b4ba8221292907b6fee04a","events":[{"type":"unfollow","webhookEventId":"01J556GQQSXGKQPFV906Q6Z5DD","deliveryContext":{"isRedelivery":false},"timestamp":1723530239228,"source":{"type":"user","userId":"U82d6fea100d7148c13eb8ccd074e0433"},"mode":"active"}]}
Request body: {"destination":"Ub4a54afea3b4ba8221292907b6fee04a","events":[{"type":"follow","follow":{"isUnblocked":true},"webhookEventId":"01J556GS2TK5H95EPC5J8M4F1F","deliveryContext":{"isRedelivery":false},"timestamp":1723530240819,"source":{"type":"user","userId":"U82d6fea100d7148c13eb8ccd074e0433"},"replyToken":"c4c427f97a29424d89819041f0d261a4","mode":"active"}]}
Request body: {"destination":"Ub4a54afea3b4ba8221292907b6fee04a","events":[{"type":"follow","follow":{"isUnblocked":true},"webhookEventId":"01J556SHWB943ARN24DJNGZ44E","deliveryContext":{"isRedelivery":false},"timestamp":1723530528472,"source":{"type":"user","userId":"U82d6fea100d7148c13eb8ccd074e0433"},"replyToken":"cae8c66e50274984986fb49927358939","mode":"active"}]}
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 104, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 115, in follow_message
    app.logger.info("Request body1: " + body)# ログ処理（記録）
                                        ^^^^
NameError: name 'body' is not defined
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 104, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 115, in follow_message
    app.logger.info("Request event1: " + event)# ログ処理（記録）
                    ~~~~~~~~~~~~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "FollowEvent") to str
Request event1: follow8bc879f883224592b7be9a6f00e5fe2a
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 104, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 121, in follow_message
    TextMessageContent(text="番号：/n待ち時間："))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for TextMessageContent
id
  field required (type=value_error.missing)
quoteToken
  field required (type=value_error.missing)
Request event1: follow60e48144a2e44d88bd3470960a82323f
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 104, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 121, in follow_message
    TextMessageContent(text="welcome"))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for TextMessageContent
id
  field required (type=value_error.missing)
quoteToken
  field required (type=value_error.missing)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 104, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 115, in follow_message
    app.logger.info("Request event1: " + event.id + event.type + event.reply_token)# ログ処理（記録）
                                         ^^^^^^^^
AttributeError: 'FollowEvent' object has no attribute 'id'
Request event1: follow57b89d6abefa4bc5a69ce686cd30c915
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 104, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 119, in follow_message
    line_bot_api.reply_message(
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/decorator.py", line 40, in wrapper_function
    return vd.call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/decorator.py", line 133, in call
    m = self.init_model_instance(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/decorator.py", line 130, in init_model_instance
    return self.model(**values)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ReplyMessage
reply_message_request
  field required (type=value_error.missing)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 104, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 115, in follow_message
    app.logger.info("Request event1: " + event.webhookEventId + event.type + event.reply_token)# ログ処理（記録）
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FollowEvent' object has no attribute 'webhookEventId'. Did you mean: 'webhook_event_id'?
Request event1: 01J55DJWSCCP57H3HYZP0CG5Q2follow3c51a1cf13c246c2bc5148bbe98d598b
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 104, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 119, in follow_message
    line_bot_api.reply_message(
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/decorator.py", line 40, in wrapper_function
    return vd.call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/decorator.py", line 133, in call
    m = self.init_model_instance(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/decorator.py", line 130, in init_model_instance
    return self.model(**values)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ReplyMessage
reply_message_request
  field required (type=value_error.missing)
Request event1: 01J55E440X4C5JYK6NYC13TY6Qfollow4fa3d82eb61f41cd907988b285c81d13
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 104, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 119, in follow_message
    line_bot_api.reply_message_with_http_info(
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/decorator.py", line 40, in wrapper_function
    return vd.call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/decorator.py", line 134, in call
    return self.execute(m)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/v1/decorator.py", line 206, in execute
    return self.raw_function(**d, **var_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/messaging/api/messaging_api.py", line 7030, in reply_message_with_http_info
    _header_params['Accept'] = self.api_client.select_header_accept(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'select_header_accept'
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 121, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 138, in handle_follow
    log_user_data(user_id, timestamp)
                  ^^^^^^^
NameError: name 'user_id' is not defined
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 124, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 141, in handle_follow
    log_user_data(user_id, timestamp)
                  ^^^^^^^
NameError: name 'user_id' is not defined
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 124, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 141, in handle_follow
    log_user_data(user_id, timestamp)
                  ^^^^^^^
NameError: name 'user_id' is not defined
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 127, in log_user_data
    timestamp = int(time.time())
                    ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 126, in log_user_data
    user_id = event.webhookEventId
              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FollowEvent' object has no attribute 'webhookEventId'. Did you mean: 'webhook_event_id'?
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 137, in handle_follow
    user_id = event.user_id
              ^^^^^^^^^^^^^
AttributeError: 'FollowEvent' object has no attribute 'user_id'
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 137, in handle_follow
    user_id = event.source.userId
              ^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserSource' object has no attribute 'userId'. Did you mean: 'user_id'?
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 147, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 113, in log_user_data
    if os.path.exists(filename):
                      ^^^^^^^^
NameError: name 'filename' is not defined
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 147, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 115, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 147, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 115, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 147, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 115, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 147, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 115, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 147, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 115, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 144, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 114, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 144, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 114, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 144, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 114, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 144, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 114, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 144, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 114, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 144, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 114, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 144, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 114, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 105, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 144, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 114, in log_user_data
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 70)
Starting to watch for changes in ./app/numbers.json...
Starting to watch for changes in ./app/numbers.json...
Starting to watch for changes in ./app/numbers.json...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
LINE Botへのメッセージ送信に失敗しました: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
LINE Botへのメッセージ送信に失敗しました: 2 validation errors for PushMessage
push_message_request
  value is not a valid dict (type=type_error.dict)
x_line_retry_key
  str type expected (type=type_error.str)
./app/numbers.jsonの変更を監視しています...
LINE Botへのメッセージ送信に失敗しました: 1 validation error for PushMessage
push_message_request
  field required (type=value_error.missing)
LINE Botへのメッセージ送信に失敗しました: 1 validation error for PushMessage
push_message_request
  field required (type=value_error.missing)
./app/numbers.jsonの変更を監視しています...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
./app/numbers.jsonの変更を監視しています...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
JSONファイルの読み込みエラー: Expecting ',' delimiter: line 3 column 5 (char 25)
JSONファイルの読み込みエラー: Expecting ',' delimiter: line 3 column 5 (char 25)
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
メッセージ処理に失敗しました: 1 validation error for ReplyMessageRequest
messages -> 0
  none is not an allowed value (type=type_error.none.not_allowed)
メッセージ処理に失敗しました: 1 validation error for ReplyMessageRequest
messages -> 0
  value is not a valid dict (type=type_error.dict)
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
メッセージ処理に失敗しました: get_value1_of_value2() missing 1 required positional argument: 'target_value2'
./app/numbers.jsonの変更を監視しています...
メッセージ処理に失敗しました: write() argument must be str, not int
./app/numbers.jsonの変更を監視しています...
メッセージ処理に失敗しました: write() argument must be str, not int
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
file change filtered...
./app/numbers.jsonの変更を監視しています...
キャンセル確認
./app/numbers.jsonの変更を監視しています...
キャンセル確認1
./app/numbers.jsonの変更を監視しています...
キャンセル確認1
./app/numbers.jsonの変更を監視しています...
メッセージ処理に失敗しました: name 'yokaku' is not defined
./app/numbers.jsonの変更を監視しています...
キャンセル確認[1]
キャンセル確認[1, 3]
./app/numbers.jsonの変更を監視しています...
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 134, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 155, in handle_follow
    data = json.loads(NUMBER_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
キャンセル確認[1]
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 2 column 17 (char 18)
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 2 column 17 (char 18)
file changed...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
キャンセル確認[12]
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
キャンセル確認[3]
キャンセル確認[3, 4]
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 161, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 180, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 43, in log_user_data
    data = [json.loads(line) for line in file]
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 161, in callback
    handler.handle(body, signature)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 227, in handle
    self.__invoke_func(func, event, payload)
  File "/usr/local/lib/python3.12/site-packages/linebot/v3/webhook.py", line 239, in __invoke_func
    func(event)
  File "/app/main.py", line 180, in handle_follow
    log_user_data(user_id, timestamp)
  File "/app/main.py", line 43, in log_user_data
    data = [json.loads(line) for line in file]
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
キャンセル確認[3]
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 2 column 17 (char 18)
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
キャンセル確認[6]
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
キャンセル確認[1]
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
キャンセル確認[1]
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
キャンセル確認[3]
キャンセル確認[3, 4]
キャンセル確認[3, 4, 5]
キャンセル確認[3, 4, 5, 6]
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
キャンセル確認[2]
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
./app/numbers.jsonの変更を監視しています...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
キャンセル確認[2]
file changed...
file change filtered...
file changed...
file change filtered...
file changed...
file changed...
file change filtered...
JSONファイルの読み込みエラー: Expecting value: line 1 column 1 (char 0)
file changed...
file change filtered...
file changed...
